---
description: Join the lab
title: Join the lab!
---

### **Prospective or current undergraduates:**
Undergraduate students are welcome to join the lab and work on a research project for course credit, for pay through the Undergraduate Research Center Research Apprenticeship Programs, or potentially as a volunteer depending on the circumstances. No specific qualifications or previous research experience are required, just enthusiasm and commitment to participate fully and respect [lab expectations](../lab_culture).

If you are interested, please read about our [project areas](../research) and **fill out [this brief Microsoft Form](https://forms.office.com/Pages/ResponsePage.aspx?id=xscRULQKq0ae9PrnSpIafwuugNwK8CdKjj1LqndxT1VURFRKREVPU0JWMk9RSzZRUjRLNzc4T0IzNC4u)** (only accessible if you are logged in with your MinnState account). Dr. Noecker will follow up with you by email. We welcome new lab members at the beginning of both fall and spring semesters, but space may be limited. 

<!-- If you are interested, please fill out [this brief Microsoft Form]() (only accessible if you are logged in with your MNSU account). Dr. Noecker will follow up with you by email.
## another nice blurb: http://zimmer.fresnostate.edu/~jross/
-->

### **Prospective M.S. students:**
Prospective M.S. students are encouraged to contact Dr. Noecker and to apply for admission to the Minnesota State Mankato [Biological Sciences M.S.](https://grad.mnsu.edu/all-graduate-programs/biology-master-of-science/) If you are interested, send an email to Dr. Noecker with your resume or C.V. and a few sentences on your educational background and why you are interested in our lab specifically. See also this [helpful guide](https://sites.google.com/view/apply-academic-positions/graduate-student) created by Dr. Lily Khadempour about how to contact a prospective graduate advisor. 

Note: Currently we are unlikely to have space for additional M.S. students for Fall 2024. You are still welcome to send a C.V. to Dr. Noecker to discuss possible options.

